_name_: celltype
dataset_name: celltype
study_dir: '/your/data/directory'
cls_key: 'celltype'
add_eos: False
batch_size: 16
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 4
shuffle: True
pin_memory: True

# Lau
studies: ['Lau_2020_PNAS']
__train_len: 87_779
# Leng
# studies: ['Leng_2021_Nat_Neurosci']
# __train_len: 37_299
# Smajic
# studies: ['Smajic_2022_brain',]
# __train_len: 25_704
# Zhu
# studies: ['Zhu_2022_bioRxiv']
# __train_len: 50_157
# Jung
# studies: ['Jung_2022_unpublished']
# __train_len: 289_376